development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: devise_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: devise_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
